[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
poem = "3.1.12"
serde = { version = "1.0.229", features = ["derive"] }
tokio = {version="1.53.1", features =["full"]}
store = { path = "../store" }
dotenvy = "0.15.7"
jsonwebtoken = {version="11.0.0",features = ["rust_crypto"]}
redis_queue = { path = "../redis_queue" }
reqwest = { version = "0.12", features = ["rustls-tls"] }
       
